# Generated by Django 5.0.4 on 2024-05-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_staffcode_profile_staff_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='staff_code',
            new_name='staffCode',
        ),
    ]
