# Generated by Django 5.0.4 on 2024-05-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_staff_code_profile_staffcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='staffCode',
            new_name='staff_code',
        ),
        migrations.AddField(
            model_name='staffcode',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
