# Generated by Django 5.0.6 on 2024-05-25 17:00

import cloudinary.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_staffcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='image'),
        ),
    ]
