# Generated by Django 5.0.6 on 2024-05-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/najb9j8ra3jxyggmx35u.png', null=True, upload_to='profiles/'),
        ),
    ]
