# Generated by Django 5.0.6 on 2024-11-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='staffcode',
            old_name='id',
            new_name='uuid',
        ),
    ]
