# Generated by Django 5.0.6 on 2024-11-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='id',
            new_name='uuid',
        ),
    ]
